# Generated by Django 4.0.4 on 2022-11-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('emergency_contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('employee_role', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hire_date', models.DateField()),
                ('is_manager', models.BooleanField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('emergency_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency_contact.emergencycontact')),
            ],
        ),
    ]
