# Generated by Django 4.0.4 on 2022-11-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='salaray',
            new_name='salary',
        ),
    ]
